# Autogenerated wrapper script for TorchCAPI_jll for aarch64-linux-gnu-cxx03
export libtorch_c_api

using Torch_jll
JLLWrappers.@generate_wrapper_header("TorchCAPI")
JLLWrappers.@declare_library_product(libtorch_c_api, "libtorch_c_api.so")
function __init__()
    JLLWrappers.@generate_init_header(Torch_jll)
    JLLWrappers.@init_library_product(
        libtorch_c_api,
        "lib/libtorch_c_api.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
