# Autogenerated wrapper script for TorchCAPI_jll for x86_64-linux-gnu-cxx03-cuda+11.3
export libtorch_c_api

using Torch_jll
using CUDA_Runtime_jll
using CUDNN_jll
JLLWrappers.@generate_wrapper_header("TorchCAPI")
JLLWrappers.@declare_library_product(libtorch_c_api, "libtorch_c_api.so")
function __init__()
    JLLWrappers.@generate_init_header(Torch_jll, CUDA_Runtime_jll, CUDNN_jll)
    JLLWrappers.@init_library_product(
        libtorch_c_api,
        "lib/libtorch_c_api.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
