# Autogenerated wrapper script for TorchCAPI_jll for x86_64-apple-darwin
export libtorch_c_api

using Torch_jll
JLLWrappers.@generate_wrapper_header("TorchCAPI")
JLLWrappers.@declare_library_product(libtorch_c_api, "@rpath/libtorch_c_api.dylib")
function __init__()
    JLLWrappers.@generate_init_header(Torch_jll)
    JLLWrappers.@init_library_product(
        libtorch_c_api,
        "lib/libtorch_c_api.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
